import { Router } from 'express';
import authRoutes from '../modules/auth/auth.route';
import userRoutes from '../modules/user/user.route';
import productRoutes from '../modules/product/product.route';
import customerRoutes from '../modules/customer/customer.route';
import supplierRoutes from '../modules/supplier/supplier.route';
import salesOrderRoutes from '../modules/sales-order/sales-order.routes';
import purchaseOrderRoutes from '../modules/purchase-order/purchase-order.routes';
import receivableRoutes from '../modules/receivable/receivable.routes';
import payableRoutes from '../modules/payable/payable.routes';
import operatingCostRoutes from '../modules/operating-cost/operating-cost.routes';
import dashboardRoutes from '../modules/dashboard/dashboard.routes';
import reportRoutes from '../modules/report/report.routes';
import alertRoutes from '../modules/alert/alert.routes';
import zaloRoutes from '../modules/zalo/zalo.route';
import invoiceRoutes from '../modules/invoice/invoice.route';
import returnRoutes from '../modules/return/return.routes';
import cashBookRoutes from '../modules/cash-book/cash-book.routes';
import chatbotRoutes from '../modules/ai/chatbot.route';
import payrollRoutes from '../modules/payroll/payroll.routes';
import uploadRoutes from '../modules/upload/upload.route';
import supplierPriceRoutes from '../modules/supplier-price/supplier-price.route';
import customerProductPriceRoutes from '../modules/customer-product-price/customer-product-price.route';
import auditLogRoutes from '../modules/audit-log/audit-log.routes';

const router = Router();

router.get('/health', (_req, res) => res.json({ status: 'ok' }));

router.use('/zalo', zaloRoutes);
router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/products', productRoutes);
router.use('/customers', customerRoutes);
router.use('/suppliers', supplierRoutes);
router.use('/sales-orders', salesOrderRoutes);
router.use('/purchase-orders', purchaseOrderRoutes);
router.use('/receivables', receivableRoutes);
router.use('/payables', payableRoutes);
router.use('/operating-costs', operatingCostRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/reports', reportRoutes);
router.use('/alerts', alertRoutes);
router.use('/invoice', invoiceRoutes);
router.use('/returns', returnRoutes);
router.use('/cash-book', cashBookRoutes);
router.use('/chatbot', chatbotRoutes);
router.use('/payroll', payrollRoutes);
router.use('/upload', uploadRoutes);
router.use('/supplier-prices', supplierPriceRoutes);
router.use('/customer-product-prices', customerProductPriceRoutes);
router.use('/audit-logs', auditLogRoutes);

export default router;
